apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-homolog
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/araujofredson/argocd-k8s.git
        revision: main
        directories:
          - path: apps/homolog/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/araujofredson/argocd-k8s.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true