apiVersion: v1
kind: Service
metadata:
  name: creator-api
  labels:
    app: creator-api
  namespace: homolog  
spec:
  type: ClusterIP
  selector:
    app: creator-api
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP