apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: social-api-ingress
  namespace: homolog
spec:
  ingressClassName: nginx
  rules:
    - host: hmlg-social.xpto.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: social-api
                port:
                  number: 8080